server:
  port: 8080
  servlet:
    #context-path: /user/loginView.do
    encoding:
      charset: UTF-8
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://18.118.169.92:3306/Movie_Schema
    username: movie
    password: Qlalfqjsgh1!
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB # default 3MB
      max-request-size: 20MB # default 50MB

devtools:
  livereload:
    enabled: true
  restart:
    enabled: true
  thymeleaf:
    cache: false


comm:
  uploadPath: /Users/kangminseon/Desktop
  maxFileCnt: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml