server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://18.118.169.92:3306/Movie_Schema
    username: movie
    password: Qlalfqjsgh1!
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB # default 3MB
      max-request-size: 20MB # default 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: l3asic0406@gmail.com
    password: qpqd rgnc kpom fdqg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  header: Authorization
  #HS512 ,64byte 이상의 secret key를 사용
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400 # ttl (초)

devtools:
  livereload:
    enabled: true
  restart:
    enabled: true
  thymeleaf:
    cache: false


comm:
  uploadPath: /Users/kangminseon/Desktop
  maxFileCnt: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml